version: '3'

services:
  postgres:
    network_mode: "host"  
    image: postgres:latest
    container_name: postgres_schule
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
  api:
    network_mode: "host"  
    container_name: schule
    image: schule:latest
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres

volumes:
  database_dockerizing:
  api_volume:
